README.md
src/.UICLEAN-BUILD.swp
src/UICLEAN-BUILD
src/__pycache__/api.cpython-313.pyc
src/__pycache__/assets_loader.cpython-313.pyc
src/__pycache__/engines.cpython-313.pyc
src/__pycache__/engines_assets.cpython-313.pyc
src/__pycache__/loaders.cpython-313.pyc
src/__pycache__/reporting.cpython-313.pyc
src/__pycache__/rmd.cpython-313.pyc
src/__pycache__/simulator.cpython-313.pyc
src/__pycache__/snapshot.cpython-313.pyc
src/api.py
src/api_types.py
src/assets.json
src/assets_loader.py
src/build-clean-run.sh
src/build-clean.sh
src/calculate_hash.py
src/clean-unneeded.sh
src/cli.py
src/conversions.py
src/eNDinomicsP1-P4
src/engines.py
src/engines_assets.py
src/favicon.ico
src/favicon.svg
src/fullvcleanbuild
src/gen_hash.py
src/hash_test.txt
src/loaders.py
src/make_benchmarks.py
src/make_favicon.py
src/output.sh
src/profiles/MyGoodProfile/allocation_yearly.json
src/profiles/MyGoodProfile/benchmarks.json
src/profiles/MyGoodProfile/economic.json
src/profiles/MyGoodProfile/income.json
src/profiles/MyGoodProfile/inflation_yearly.json
src/profiles/MyGoodProfile/person.json
src/profiles/MyGoodProfile/rmd.json
src/profiles/MyGoodProfile/shocks_yearly.json
src/profiles/MyGoodProfile/taxes_states_mfj_single.json
src/profiles/MyGoodProfile/withdrawal_schedule.json
src/profiles/Test 2/allocation_yearly.json
src/profiles/Test 2/benchmarks.json
src/profiles/Test 2/economic.json
src/profiles/Test 2/income.json
src/profiles/Test 2/inflation_yearly.json
src/profiles/Test 2/person.json
src/profiles/Test 2/rmd.json
src/profiles/Test 2/shocks_yearly.json
src/profiles/Test 2/taxes_states_mfj_single.json
src/profiles/Test 2/withdrawal_schedule.json
src/profiles/Test-3/allocation_yearly.json
src/profiles/Test-3/benchmarks.json
src/profiles/Test-3/economic.json
src/profiles/Test-3/income.json
src/profiles/Test-3/inflation_yearly.json
src/profiles/Test-3/person.json
src/profiles/Test-3/rmd.json
src/profiles/Test-3/shocks_yearly.json
src/profiles/Test-3/taxes_states_mfj_single.json
src/profiles/Test-3/withdrawal_schedule.json
src/profiles/Test-profile/allocation_yearly.json
src/profiles/Test-profile/benchmarks.json
src/profiles/Test-profile/economic.json
src/profiles/Test-profile/income.json
src/profiles/Test-profile/inflation_yearly.json
src/profiles/Test-profile/person.json
src/profiles/Test-profile/rmd.json
src/profiles/Test-profile/shocks_yearly.json
src/profiles/Test-profile/taxes_states_mfj_single.json
src/profiles/Test-profile/withdrawal_schedule.json
src/profiles/default/allocation_yearly.json
src/profiles/default/allocation_yearly.json.original
src/profiles/default/benchmarks.json
src/profiles/default/economic.json
src/profiles/default/income.json
src/profiles/default/inflation_yearly.json
src/profiles/default/person.json
src/profiles/default/reports/run_20260202_170546/accounts_current_investment_yoy.csv
src/profiles/default/reports/run_20260202_170546/accounts_future_investment_yoy.csv
src/profiles/default/reports/run_20260202_170546/portfolio_current_summary.png
src/profiles/default/reports/run_20260202_170546/portfolio_future_summary.png
src/profiles/default/reports/run_20260202_170546/raw_snapshot_accounts.json
src/profiles/default/reports/run_20260202_170546/rmd_current_components.png
src/profiles/default/reports/run_20260202_170546/run_meta.json
src/profiles/default/reports/run_20260202_170546/shocks_override.json
src/profiles/default/reports/run_20260202_170546/taxes_current_components.png
src/profiles/default/reports/run_20260202_170546/taxes_rmd_current_by_year.csv
src/profiles/default/reports/run_20260202_170546/totals_current.csv
src/profiles/default/reports/run_20260202_170546/totals_future.csv
src/profiles/default/rmd.json
src/profiles/default/shocks_yearly.json
src/profiles/default/taxes_states_mfj_single.json
src/profiles/default/withdrawal_schedule.json
src/readme-updating-assetsjson
src/reporting.py
src/rmd.py
src/run-retire
src/run-retire-debug
src/run-retire.sh
src/run_retirement_analysis_on_snapshot
src/sh-run-retire
src/simulator.py
src/snapshot.py
src/test.json
src/ui/dist/assets/index-IYaTbswW.css
src/ui/dist/assets/index-S58GUZYR.js
src/ui/dist/favicon.ico
src/ui/dist/index.html
src/ui/index.html
src/ui/main.tsx
src/ui/node_modules/.bin/esbuild
src/ui/node_modules/.bin/loose-envify
src/ui/node_modules/.bin/nanoid
src/ui/node_modules/.bin/rollup
src/ui/node_modules/.bin/tsc
src/ui/node_modules/.bin/tsserver
src/ui/node_modules/.bin/vite
src/ui/node_modules/.package-lock.json
src/ui/node_modules/@esbuild/darwin-arm64/README.md
src/ui/node_modules/@esbuild/darwin-arm64/bin/esbuild
src/ui/node_modules/@esbuild/darwin-arm64/package.json
src/ui/node_modules/@rolldown/pluginutils/LICENSE
src/ui/node_modules/@rolldown/pluginutils/dist/index.cjs
src/ui/node_modules/@rolldown/pluginutils/dist/index.d.cts
src/ui/node_modules/@rolldown/pluginutils/dist/index.d.ts
src/ui/node_modules/@rolldown/pluginutils/dist/index.js
src/ui/node_modules/@rolldown/pluginutils/package.json
src/ui/node_modules/@rollup/rollup-darwin-arm64/README.md
src/ui/node_modules/@rollup/rollup-darwin-arm64/package.json
src/ui/node_modules/@rollup/rollup-darwin-arm64/rollup.darwin-arm64.node
src/ui/node_modules/@swc/core-darwin-arm64/README.md
src/ui/node_modules/@swc/core-darwin-arm64/package.json
src/ui/node_modules/@swc/core-darwin-arm64/swc.darwin-arm64.node
src/ui/node_modules/@swc/core/README.md
src/ui/node_modules/@swc/core/Visitor.d.ts
src/ui/node_modules/@swc/core/Visitor.js
src/ui/node_modules/@swc/core/binding.d.ts
src/ui/node_modules/@swc/core/binding.js
src/ui/node_modules/@swc/core/index.d.ts
src/ui/node_modules/@swc/core/index.js
src/ui/node_modules/@swc/core/package.json
src/ui/node_modules/@swc/core/postinstall.js
src/ui/node_modules/@swc/core/spack.d.ts
src/ui/node_modules/@swc/core/spack.js
src/ui/node_modules/@swc/core/util.d.ts
src/ui/node_modules/@swc/core/util.js
src/ui/node_modules/@swc/counter/CHANGELOG.md
src/ui/node_modules/@swc/counter/README.md
src/ui/node_modules/@swc/counter/index.js
src/ui/node_modules/@swc/counter/package.json
src/ui/node_modules/@swc/types/LICENSE
src/ui/node_modules/@swc/types/README.md
src/ui/node_modules/@swc/types/assumptions.d.ts
src/ui/node_modules/@swc/types/assumptions.js
src/ui/node_modules/@swc/types/index.d.ts
src/ui/node_modules/@swc/types/index.js
src/ui/node_modules/@swc/types/package.json
src/ui/node_modules/@types/estree/LICENSE
src/ui/node_modules/@types/estree/README.md
src/ui/node_modules/@types/estree/flow.d.ts
src/ui/node_modules/@types/estree/index.d.ts
src/ui/node_modules/@types/estree/package.json
src/ui/node_modules/@types/prop-types/LICENSE
src/ui/node_modules/@types/prop-types/README.md
src/ui/node_modules/@types/prop-types/index.d.ts
src/ui/node_modules/@types/prop-types/package.json
src/ui/node_modules/@types/react-dom/LICENSE
src/ui/node_modules/@types/react-dom/README.md
src/ui/node_modules/@types/react-dom/canary.d.ts
src/ui/node_modules/@types/react-dom/client.d.ts
src/ui/node_modules/@types/react-dom/experimental.d.ts
src/ui/node_modules/@types/react-dom/index.d.ts
src/ui/node_modules/@types/react-dom/package.json
src/ui/node_modules/@types/react-dom/server.d.ts
src/ui/node_modules/@types/react-dom/test-utils/index.d.ts
src/ui/node_modules/@types/react/LICENSE
src/ui/node_modules/@types/react/README.md
src/ui/node_modules/@types/react/canary.d.ts
src/ui/node_modules/@types/react/experimental.d.ts
src/ui/node_modules/@types/react/global.d.ts
src/ui/node_modules/@types/react/index.d.ts
src/ui/node_modules/@types/react/jsx-dev-runtime.d.ts
src/ui/node_modules/@types/react/jsx-runtime.d.ts
src/ui/node_modules/@types/react/package.json
src/ui/node_modules/@types/react/ts5.0/canary.d.ts
src/ui/node_modules/@types/react/ts5.0/experimental.d.ts
src/ui/node_modules/@types/react/ts5.0/global.d.ts
src/ui/node_modules/@types/react/ts5.0/index.d.ts
src/ui/node_modules/@types/react/ts5.0/jsx-dev-runtime.d.ts
src/ui/node_modules/@types/react/ts5.0/jsx-runtime.d.ts
src/ui/node_modules/@vitejs/plugin-react-swc/LICENSE
src/ui/node_modules/@vitejs/plugin-react-swc/README.md
src/ui/node_modules/@vitejs/plugin-react-swc/index.cjs
src/ui/node_modules/@vitejs/plugin-react-swc/index.d.cts
src/ui/node_modules/@vitejs/plugin-react-swc/index.d.ts
src/ui/node_modules/@vitejs/plugin-react-swc/index.js
src/ui/node_modules/@vitejs/plugin-react-swc/package.json
src/ui/node_modules/@vitejs/plugin-react-swc/refresh-runtime.js
src/ui/node_modules/csstype/LICENSE
src/ui/node_modules/csstype/README.md
src/ui/node_modules/csstype/index.d.ts
src/ui/node_modules/csstype/index.js.flow
src/ui/node_modules/csstype/package.json
src/ui/node_modules/esbuild/LICENSE.md
src/ui/node_modules/esbuild/README.md
src/ui/node_modules/esbuild/bin/esbuild
src/ui/node_modules/esbuild/install.js
src/ui/node_modules/esbuild/lib/main.d.ts
src/ui/node_modules/esbuild/lib/main.js
src/ui/node_modules/esbuild/package.json
src/ui/node_modules/fdir/LICENSE
src/ui/node_modules/fdir/README.md
src/ui/node_modules/fdir/dist/index.cjs
src/ui/node_modules/fdir/dist/index.d.cts
src/ui/node_modules/fdir/dist/index.d.mts
src/ui/node_modules/fdir/dist/index.mjs
src/ui/node_modules/fdir/package.json
src/ui/node_modules/js-tokens/CHANGELOG.md
src/ui/node_modules/js-tokens/LICENSE
src/ui/node_modules/js-tokens/README.md
src/ui/node_modules/js-tokens/index.js
src/ui/node_modules/js-tokens/package.json
src/ui/node_modules/loose-envify/LICENSE
src/ui/node_modules/loose-envify/README.md
src/ui/node_modules/loose-envify/cli.js
src/ui/node_modules/loose-envify/custom.js
src/ui/node_modules/loose-envify/index.js
src/ui/node_modules/loose-envify/loose-envify.js
src/ui/node_modules/loose-envify/package.json
src/ui/node_modules/loose-envify/replace.js
src/ui/node_modules/nanoid/LICENSE
src/ui/node_modules/nanoid/README.md
src/ui/node_modules/nanoid/async/index.browser.cjs
src/ui/node_modules/nanoid/async/index.browser.js
src/ui/node_modules/nanoid/async/index.cjs
src/ui/node_modules/nanoid/async/index.d.ts
src/ui/node_modules/nanoid/async/index.js
src/ui/node_modules/nanoid/async/index.native.js
src/ui/node_modules/nanoid/async/package.json
src/ui/node_modules/nanoid/bin/nanoid.cjs
src/ui/node_modules/nanoid/index.browser.cjs
src/ui/node_modules/nanoid/index.browser.js
src/ui/node_modules/nanoid/index.cjs
src/ui/node_modules/nanoid/index.d.cts
src/ui/node_modules/nanoid/index.d.ts
src/ui/node_modules/nanoid/index.js
src/ui/node_modules/nanoid/nanoid.js
src/ui/node_modules/nanoid/non-secure/index.cjs
src/ui/node_modules/nanoid/non-secure/index.d.ts
src/ui/node_modules/nanoid/non-secure/index.js
src/ui/node_modules/nanoid/non-secure/package.json
src/ui/node_modules/nanoid/package.json
src/ui/node_modules/nanoid/url-alphabet/index.cjs
src/ui/node_modules/nanoid/url-alphabet/index.js
src/ui/node_modules/nanoid/url-alphabet/package.json
src/ui/node_modules/picocolors/LICENSE
src/ui/node_modules/picocolors/README.md
src/ui/node_modules/picocolors/package.json
src/ui/node_modules/picocolors/picocolors.browser.js
src/ui/node_modules/picocolors/picocolors.d.ts
src/ui/node_modules/picocolors/picocolors.js
src/ui/node_modules/picocolors/types.d.ts
src/ui/node_modules/picomatch/LICENSE
src/ui/node_modules/picomatch/README.md
src/ui/node_modules/picomatch/index.js
src/ui/node_modules/picomatch/lib/constants.js
src/ui/node_modules/picomatch/lib/parse.js
src/ui/node_modules/picomatch/lib/picomatch.js
src/ui/node_modules/picomatch/lib/scan.js
src/ui/node_modules/picomatch/lib/utils.js
src/ui/node_modules/picomatch/package.json
src/ui/node_modules/picomatch/posix.js
src/ui/node_modules/postcss/LICENSE
src/ui/node_modules/postcss/README.md
src/ui/node_modules/postcss/lib/at-rule.d.ts
src/ui/node_modules/postcss/lib/at-rule.js
src/ui/node_modules/postcss/lib/comment.d.ts
src/ui/node_modules/postcss/lib/comment.js
src/ui/node_modules/postcss/lib/container.d.ts
src/ui/node_modules/postcss/lib/container.js
src/ui/node_modules/postcss/lib/css-syntax-error.d.ts
src/ui/node_modules/postcss/lib/css-syntax-error.js
src/ui/node_modules/postcss/lib/declaration.d.ts
src/ui/node_modules/postcss/lib/declaration.js
src/ui/node_modules/postcss/lib/document.d.ts
src/ui/node_modules/postcss/lib/document.js
src/ui/node_modules/postcss/lib/fromJSON.d.ts
src/ui/node_modules/postcss/lib/fromJSON.js
src/ui/node_modules/postcss/lib/input.d.ts
src/ui/node_modules/postcss/lib/input.js
src/ui/node_modules/postcss/lib/lazy-result.d.ts
src/ui/node_modules/postcss/lib/lazy-result.js
src/ui/node_modules/postcss/lib/list.d.ts
src/ui/node_modules/postcss/lib/list.js
src/ui/node_modules/postcss/lib/map-generator.js
src/ui/node_modules/postcss/lib/no-work-result.d.ts
src/ui/node_modules/postcss/lib/no-work-result.js
src/ui/node_modules/postcss/lib/node.d.ts
src/ui/node_modules/postcss/lib/node.js
src/ui/node_modules/postcss/lib/parse.d.ts
src/ui/node_modules/postcss/lib/parse.js
src/ui/node_modules/postcss/lib/parser.js
src/ui/node_modules/postcss/lib/postcss.d.mts
src/ui/node_modules/postcss/lib/postcss.d.ts
src/ui/node_modules/postcss/lib/postcss.js
src/ui/node_modules/postcss/lib/postcss.mjs
src/ui/node_modules/postcss/lib/previous-map.d.ts
src/ui/node_modules/postcss/lib/previous-map.js
src/ui/node_modules/postcss/lib/processor.d.ts
src/ui/node_modules/postcss/lib/processor.js
src/ui/node_modules/postcss/lib/result.d.ts
src/ui/node_modules/postcss/lib/result.js
src/ui/node_modules/postcss/lib/root.d.ts
src/ui/node_modules/postcss/lib/root.js
src/ui/node_modules/postcss/lib/rule.d.ts
src/ui/node_modules/postcss/lib/rule.js
src/ui/node_modules/postcss/lib/stringifier.d.ts
src/ui/node_modules/postcss/lib/stringifier.js
src/ui/node_modules/postcss/lib/stringify.d.ts
src/ui/node_modules/postcss/lib/stringify.js
src/ui/node_modules/postcss/lib/symbols.js
src/ui/node_modules/postcss/lib/terminal-highlight.js
src/ui/node_modules/postcss/lib/tokenize.js
src/ui/node_modules/postcss/lib/warn-once.js
src/ui/node_modules/postcss/lib/warning.d.ts
src/ui/node_modules/postcss/lib/warning.js
src/ui/node_modules/postcss/package.json
src/ui/node_modules/react-dom/LICENSE
src/ui/node_modules/react-dom/README.md
src/ui/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js
src/ui/node_modules/react-dom/cjs/react-dom-server-legacy.browser.production.min.js
src/ui/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js
src/ui/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js
src/ui/node_modules/react-dom/cjs/react-dom-server.browser.development.js
src/ui/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js
src/ui/node_modules/react-dom/cjs/react-dom-server.node.development.js
src/ui/node_modules/react-dom/cjs/react-dom-server.node.production.min.js
src/ui/node_modules/react-dom/cjs/react-dom-test-utils.development.js
src/ui/node_modules/react-dom/cjs/react-dom-test-utils.production.min.js
src/ui/node_modules/react-dom/cjs/react-dom.development.js
src/ui/node_modules/react-dom/cjs/react-dom.production.min.js
src/ui/node_modules/react-dom/cjs/react-dom.profiling.min.js
src/ui/node_modules/react-dom/client.js
src/ui/node_modules/react-dom/index.js
src/ui/node_modules/react-dom/package.json
src/ui/node_modules/react-dom/profiling.js
src/ui/node_modules/react-dom/server.browser.js
src/ui/node_modules/react-dom/server.js
src/ui/node_modules/react-dom/server.node.js
src/ui/node_modules/react-dom/test-utils.js
src/ui/node_modules/react-dom/umd/react-dom-server-legacy.browser.development.js
src/ui/node_modules/react-dom/umd/react-dom-server-legacy.browser.production.min.js
src/ui/node_modules/react-dom/umd/react-dom-server.browser.development.js
src/ui/node_modules/react-dom/umd/react-dom-server.browser.production.min.js
src/ui/node_modules/react-dom/umd/react-dom-test-utils.development.js
src/ui/node_modules/react-dom/umd/react-dom-test-utils.production.min.js
src/ui/node_modules/react-dom/umd/react-dom.development.js
src/ui/node_modules/react-dom/umd/react-dom.production.min.js
src/ui/node_modules/react-dom/umd/react-dom.profiling.min.js
src/ui/node_modules/react/LICENSE
src/ui/node_modules/react/README.md
src/ui/node_modules/react/cjs/react-jsx-dev-runtime.development.js
src/ui/node_modules/react/cjs/react-jsx-dev-runtime.production.min.js
src/ui/node_modules/react/cjs/react-jsx-dev-runtime.profiling.min.js
src/ui/node_modules/react/cjs/react-jsx-runtime.development.js
src/ui/node_modules/react/cjs/react-jsx-runtime.production.min.js
src/ui/node_modules/react/cjs/react-jsx-runtime.profiling.min.js
src/ui/node_modules/react/cjs/react.development.js
src/ui/node_modules/react/cjs/react.production.min.js
src/ui/node_modules/react/cjs/react.shared-subset.development.js
src/ui/node_modules/react/cjs/react.shared-subset.production.min.js
src/ui/node_modules/react/index.js
src/ui/node_modules/react/jsx-dev-runtime.js
src/ui/node_modules/react/jsx-runtime.js
src/ui/node_modules/react/package.json
src/ui/node_modules/react/react.shared-subset.js
src/ui/node_modules/react/umd/react.development.js
src/ui/node_modules/react/umd/react.production.min.js
src/ui/node_modules/react/umd/react.profiling.min.js
src/ui/node_modules/rollup/LICENSE.md
src/ui/node_modules/rollup/README.md
src/ui/node_modules/rollup/dist/bin/rollup
src/ui/node_modules/rollup/dist/es/getLogFilter.js
src/ui/node_modules/rollup/dist/es/package.json
src/ui/node_modules/rollup/dist/es/parseAst.js
src/ui/node_modules/rollup/dist/es/rollup.js
src/ui/node_modules/rollup/dist/es/shared/node-entry.js
src/ui/node_modules/rollup/dist/es/shared/parseAst.js
src/ui/node_modules/rollup/dist/es/shared/watch.js
src/ui/node_modules/rollup/dist/getLogFilter.d.ts
src/ui/node_modules/rollup/dist/getLogFilter.js
src/ui/node_modules/rollup/dist/loadConfigFile.d.ts
src/ui/node_modules/rollup/dist/loadConfigFile.js
src/ui/node_modules/rollup/dist/native.js
src/ui/node_modules/rollup/dist/parseAst.d.ts
src/ui/node_modules/rollup/dist/parseAst.js
src/ui/node_modules/rollup/dist/rollup.d.ts
src/ui/node_modules/rollup/dist/rollup.js
src/ui/node_modules/rollup/dist/shared/fsevents-importer.js
src/ui/node_modules/rollup/dist/shared/index.js
src/ui/node_modules/rollup/dist/shared/loadConfigFile.js
src/ui/node_modules/rollup/dist/shared/parseAst.js
src/ui/node_modules/rollup/dist/shared/rollup.js
src/ui/node_modules/rollup/dist/shared/watch-cli.js
src/ui/node_modules/rollup/dist/shared/watch.js
src/ui/node_modules/rollup/package.json
src/ui/node_modules/scheduler/LICENSE
src/ui/node_modules/scheduler/README.md
src/ui/node_modules/scheduler/cjs/scheduler-unstable_mock.development.js
src/ui/node_modules/scheduler/cjs/scheduler-unstable_mock.production.min.js
src/ui/node_modules/scheduler/cjs/scheduler-unstable_post_task.development.js
src/ui/node_modules/scheduler/cjs/scheduler-unstable_post_task.production.min.js
src/ui/node_modules/scheduler/cjs/scheduler.development.js
src/ui/node_modules/scheduler/cjs/scheduler.production.min.js
src/ui/node_modules/scheduler/index.js
src/ui/node_modules/scheduler/package.json
src/ui/node_modules/scheduler/umd/scheduler-unstable_mock.development.js
src/ui/node_modules/scheduler/umd/scheduler-unstable_mock.production.min.js
src/ui/node_modules/scheduler/umd/scheduler.development.js
src/ui/node_modules/scheduler/umd/scheduler.production.min.js
src/ui/node_modules/scheduler/umd/scheduler.profiling.min.js
src/ui/node_modules/scheduler/unstable_mock.js
src/ui/node_modules/scheduler/unstable_post_task.js
src/ui/node_modules/source-map-js/LICENSE
src/ui/node_modules/source-map-js/README.md
src/ui/node_modules/source-map-js/lib/array-set.js
src/ui/node_modules/source-map-js/lib/base64-vlq.js
src/ui/node_modules/source-map-js/lib/base64.js
src/ui/node_modules/source-map-js/lib/binary-search.js
src/ui/node_modules/source-map-js/lib/mapping-list.js
src/ui/node_modules/source-map-js/lib/quick-sort.js
src/ui/node_modules/source-map-js/lib/source-map-consumer.d.ts
src/ui/node_modules/source-map-js/lib/source-map-consumer.js
src/ui/node_modules/source-map-js/lib/source-map-generator.d.ts
src/ui/node_modules/source-map-js/lib/source-map-generator.js
src/ui/node_modules/source-map-js/lib/source-node.d.ts
src/ui/node_modules/source-map-js/lib/source-node.js
src/ui/node_modules/source-map-js/lib/util.js
src/ui/node_modules/source-map-js/package.json
src/ui/node_modules/source-map-js/source-map.d.ts
src/ui/node_modules/source-map-js/source-map.js
src/ui/node_modules/tinyglobby/LICENSE
src/ui/node_modules/tinyglobby/README.md
src/ui/node_modules/tinyglobby/dist/index.cjs
src/ui/node_modules/tinyglobby/dist/index.d.cts
src/ui/node_modules/tinyglobby/dist/index.d.mts
src/ui/node_modules/tinyglobby/dist/index.mjs
src/ui/node_modules/tinyglobby/package.json
src/ui/node_modules/typescript/LICENSE.txt
src/ui/node_modules/typescript/README.md
src/ui/node_modules/typescript/SECURITY.md
src/ui/node_modules/typescript/ThirdPartyNoticeText.txt
src/ui/node_modules/typescript/bin/tsc
src/ui/node_modules/typescript/bin/tsserver
src/ui/node_modules/typescript/lib/_tsc.js
src/ui/node_modules/typescript/lib/_tsserver.js
src/ui/node_modules/typescript/lib/_typingsInstaller.js
src/ui/node_modules/typescript/lib/cs/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/de/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/es/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/fr/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/it/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/ja/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/ko/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/lib.d.ts
src/ui/node_modules/typescript/lib/lib.decorators.d.ts
src/ui/node_modules/typescript/lib/lib.decorators.legacy.d.ts
src/ui/node_modules/typescript/lib/lib.dom.asynciterable.d.ts
src/ui/node_modules/typescript/lib/lib.dom.d.ts
src/ui/node_modules/typescript/lib/lib.dom.iterable.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.collection.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.core.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.generator.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.iterable.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.promise.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.proxy.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.reflect.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.symbol.d.ts
src/ui/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
src/ui/node_modules/typescript/lib/lib.es2016.array.include.d.ts
src/ui/node_modules/typescript/lib/lib.es2016.d.ts
src/ui/node_modules/typescript/lib/lib.es2016.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2016.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.arraybuffer.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.date.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.object.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.string.d.ts
src/ui/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts
src/ui/node_modules/typescript/lib/lib.es2018.asyncgenerator.d.ts
src/ui/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts
src/ui/node_modules/typescript/lib/lib.es2018.d.ts
src/ui/node_modules/typescript/lib/lib.es2018.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2018.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2018.promise.d.ts
src/ui/node_modules/typescript/lib/lib.es2018.regexp.d.ts
src/ui/node_modules/typescript/lib/lib.es2019.array.d.ts
src/ui/node_modules/typescript/lib/lib.es2019.d.ts
src/ui/node_modules/typescript/lib/lib.es2019.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2019.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2019.object.d.ts
src/ui/node_modules/typescript/lib/lib.es2019.string.d.ts
src/ui/node_modules/typescript/lib/lib.es2019.symbol.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.bigint.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.date.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.number.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.promise.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.sharedmemory.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.string.d.ts
src/ui/node_modules/typescript/lib/lib.es2020.symbol.wellknown.d.ts
src/ui/node_modules/typescript/lib/lib.es2021.d.ts
src/ui/node_modules/typescript/lib/lib.es2021.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2021.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2021.promise.d.ts
src/ui/node_modules/typescript/lib/lib.es2021.string.d.ts
src/ui/node_modules/typescript/lib/lib.es2021.weakref.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.array.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.error.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.object.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.regexp.d.ts
src/ui/node_modules/typescript/lib/lib.es2022.string.d.ts
src/ui/node_modules/typescript/lib/lib.es2023.array.d.ts
src/ui/node_modules/typescript/lib/lib.es2023.collection.d.ts
src/ui/node_modules/typescript/lib/lib.es2023.d.ts
src/ui/node_modules/typescript/lib/lib.es2023.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2023.intl.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.arraybuffer.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.collection.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.full.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.object.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.promise.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.regexp.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.sharedmemory.d.ts
src/ui/node_modules/typescript/lib/lib.es2024.string.d.ts
src/ui/node_modules/typescript/lib/lib.es5.d.ts
src/ui/node_modules/typescript/lib/lib.es6.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.array.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.collection.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.decorators.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.disposable.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.error.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.float16.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.full.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.intl.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.iterator.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.promise.d.ts
src/ui/node_modules/typescript/lib/lib.esnext.sharedmemory.d.ts
src/ui/node_modules/typescript/lib/lib.scripthost.d.ts
src/ui/node_modules/typescript/lib/lib.webworker.asynciterable.d.ts
src/ui/node_modules/typescript/lib/lib.webworker.d.ts
src/ui/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
src/ui/node_modules/typescript/lib/lib.webworker.iterable.d.ts
src/ui/node_modules/typescript/lib/pl/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/pt-br/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/ru/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/tr/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/tsc.js
src/ui/node_modules/typescript/lib/tsserver.js
src/ui/node_modules/typescript/lib/tsserverlibrary.d.ts
src/ui/node_modules/typescript/lib/tsserverlibrary.js
src/ui/node_modules/typescript/lib/typesMap.json
src/ui/node_modules/typescript/lib/typescript.d.ts
src/ui/node_modules/typescript/lib/typescript.js
src/ui/node_modules/typescript/lib/typingsInstaller.js
src/ui/node_modules/typescript/lib/watchGuard.js
src/ui/node_modules/typescript/lib/zh-cn/diagnosticMessages.generated.json
src/ui/node_modules/typescript/lib/zh-tw/diagnosticMessages.generated.json
src/ui/node_modules/typescript/package.json
src/ui/node_modules/vite/LICENSE.md
src/ui/node_modules/vite/README.md
src/ui/node_modules/vite/bin/openChrome.applescript
src/ui/node_modules/vite/bin/vite.js
src/ui/node_modules/vite/client.d.ts
src/ui/node_modules/vite/dist/client/client.mjs
src/ui/node_modules/vite/dist/client/env.mjs
src/ui/node_modules/vite/dist/node-cjs/publicUtils.cjs
src/ui/node_modules/vite/dist/node/chunks/dep-3RmXg9uo.js
src/ui/node_modules/vite/dist/node/chunks/dep-C9BXG1mU.js
src/ui/node_modules/vite/dist/node/chunks/dep-CvfTChi5.js
src/ui/node_modules/vite/dist/node/chunks/dep-D4NMHUTW.js
src/ui/node_modules/vite/dist/node/chunks/dep-DWMUTS1A.js
src/ui/node_modules/vite/dist/node/cli.js
src/ui/node_modules/vite/dist/node/constants.js
src/ui/node_modules/vite/dist/node/index.d.ts
src/ui/node_modules/vite/dist/node/index.js
src/ui/node_modules/vite/dist/node/module-runner.d.ts
src/ui/node_modules/vite/dist/node/module-runner.js
src/ui/node_modules/vite/dist/node/moduleRunnerTransport.d-DJ_mE5sf.d.ts
src/ui/node_modules/vite/index.cjs
src/ui/node_modules/vite/index.d.cts
src/ui/node_modules/vite/misc/false.js
src/ui/node_modules/vite/misc/true.js
src/ui/node_modules/vite/package.json
src/ui/node_modules/vite/types/customEvent.d.ts
src/ui/node_modules/vite/types/hmrPayload.d.ts
src/ui/node_modules/vite/types/hot.d.ts
src/ui/node_modules/vite/types/import-meta.d.ts
src/ui/node_modules/vite/types/importGlob.d.ts
src/ui/node_modules/vite/types/importMeta.d.ts
src/ui/node_modules/vite/types/internal/cssPreprocessorOptions.d.ts
src/ui/node_modules/vite/types/internal/lightningcssOptions.d.ts
src/ui/node_modules/vite/types/metadata.d.ts
src/ui/node_modules/vite/types/package.json
src/ui/package-lock.json
src/ui/package.json
src/ui/src/App.tsx
src/ui/src/App.tsx.new
src/ui/src/App.tsx.v104
src/ui/src/App.tsx.v105
src/ui/src/lastworkingAndCurrent.sh
src/ui/src/main.tsx
src/ui/src/styles.css
src/ui/src/styles.css.backup-v1
src/ui/tsconfig.json
src/ui/vite.config.ts
src/vcleanbld_ui
src/verify-ui-results.sh
src/verify_hash_pair.py
src/view-latest-results.sh
